# -*- coding: utf-8 -*-
"""AIDI2004_LAB4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jlj-GpJu4EUgyATNZBZW20RJAhd0shvv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Fish.csv')
df.head()

print(df.isnull().sum())
df.dtypes

sns.pairplot(df)

df.features = df.drop(columns='Species')
print(df.features)
df.results = df['Species']
print(df.results)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(n_estimators=100)

x_train, x_test, y_train, y_test = train_test_split(df.features, df.results, test_size=.15)

def get_model(model, x_train, x_test, y_train, y_test):
  model.fit(x_train, y_train)
  return model.predict(x_test), accuracy_score(model.predict(x_test),y_test)

print(get_model(rf, x_train, x_test, y_train, y_test))

classifier = rf.fit(df.features, df.results)

y_pred = classifier.predict(x_test)
print(y_pred)

print(accuracy_score(y_pred, y_test))

import pickle
pickle_out = open('classifier.pkl', 'wb')
pickle.dump(classifier, pickle_out)
pickle_out.close()

print(classifier.predict([[19.9, 13.8, 15.0, 16.2, 2.9322, 1.8792]]))